CREATE TABLE users (
    id INTEGER PRIMARY KEY NOT NULL,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE devices (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    device_id VARCHAR(255) NOT NULL UNIQUE, 
    name VARCHAR(255),
    manufacturer VARCHAR(255),
    model VARCHAR(255)
);

CREATE TABLE device_tokens (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    device_id INTEGER NOT NULL UNIQUE,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    expires_at DATETIME,
    last_used_at DATETIME,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(device_id) REFERENCES devices(id) ON DELETE CASCADE
);

CREATE TABLE entities (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    entity_id VARCHAR(255) NOT NULL UNIQUE,
    device_id INTEGER,
    friendly_name VARCHAR(255),
    platform VARCHAR(255),
    FOREIGN KEY(device_id) REFERENCES devices(id) ON DELETE CASCADE
);

CREATE TABLE states_meta (
    metadata_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    entity_id VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE states (
    state_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    metadata_id INTEGER,
    state VARCHAR(255),
    attributes TEXT,
    last_changed DATETIME,
    last_updated DATETIME,
    created DATETIME,
    FOREIGN KEY(metadata_id) REFERENCES states_meta(metadata_id)
);

CREATE TABLE events (
    event_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    event_type VARCHAR(64),
    event_data TEXT,
    origin VARCHAR(32),
    time_fired DATETIME
);

CREATE TABLE entities_configurations (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    entity_id INTEGER NOT NULL UNIQUE,
    configuration TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(entity_id) REFERENCES entities(id) ON DELETE CASCADE
);

CREATE TABLE system_configurations (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    key VARCHAR(255) NOT NULL UNIQUE,
    value TEXT NOT NULL,
    enabled INTEGER NOT NULL DEFAULT 1 CHECK(enabled IN (0, 1)),
    description TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE flows (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    enabled INTEGER NOT NULL DEFAULT 1 CHECK(enabled IN (0, 1)),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE flow_versions (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    flow_id INTEGER NOT NULL,
    version INTEGER NOT NULL,
    graph_json TEXT NOT NULL,
    comment TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(flow_id) REFERENCES flows(id) ON DELETE CASCADE,
    UNIQUE(flow_id, version)
);