name: Rust

# on:
#   push:
#     branches: ["main"]
#   pull_request:
#     branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  BINARY_NAME: server

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libglib2.0-dev pkg-config libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev

      - name: Install npm dependencies
        run: npm install

      - name: Build
        run: cargo build --release --verbose
        working-directory: ./apps/server

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BINARY_NAME }}
          path: target/release/${{ env.BINARY_NAME }}
